defmodule AccessGuardian.Repo.Migrations.CreateCatalog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :email, :citext, null: false
      add :full_name, :text, null: false
      add :department, :text
      add :job_title, :text
      add :manager_id, :uuid
      add :slack_user_id, :text
      add :org_role, :text, null: false, default: "user"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:organization_id, :email],
             name: "users_unique_email_per_org_index"
           )

    create table(:resources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :application_id, :uuid, null: false
      add :name, :text, null: false
      add :parent_resource_id, :uuid
      add :is_mandatory, :boolean, default: false
      add :is_requestable, :boolean, default: true
    end

    create table(:permissions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :resource_id,
          references(:resources,
            column: :id,
            name: "permissions_resource_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :name, :text, null: false
      add :selection_type, :text, null: false, default: "single"
    end

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:users) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "users_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :manager_id,
             references(:users,
               column: :id,
               name: "users_manager_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organizations) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :slack_hr_channel_id, :text
      add :slack_admin_channel_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    create table(:approval_steps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :approval_policy_id, :uuid, null: false
      add :step_index, :bigint, null: false
      add :approver_type, :text, null: false
      add :specific_user_id, :uuid
      add :response_mode, :text, null: false, default: "first_to_respond"
    end

    create table(:approval_policies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:approval_steps) do
      modify :approval_policy_id,
             references(:approval_policies,
               column: :id,
               name: "approval_steps_approval_policy_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:approval_policies) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "approval_policies_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :name, :text, null: false
      add :is_default, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:applications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:resources) do
      modify :application_id,
             references(:applications,
               column: :id,
               name: "resources_application_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :parent_resource_id,
             references(:resources,
               column: :id,
               name: "resources_parent_resource_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:applications) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "applications_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :name, :text, null: false
      add :status, :text, null: false, default: "assigned"
      add :integration_type, :text, null: false, default: "manual"

      add :business_owner_id,
          references(:users,
            column: :id,
            name: "applications_business_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :approval_policy_id,
          references(:approval_policies,
            column: :id,
            name: "applications_approval_policy_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:application_admin_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :application_id,
          references(:applications,
            column: :id,
            name: "application_admin_assignments_application_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "application_admin_assignments_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:application_admin_assignments, [:application_id, :user_id],
             name: "application_admin_assignments_unique_admin_assignment_index"
           )

    create table(:app_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid, null: false
      add :application_id, :uuid, null: false
      add :status, :text, null: false, default: "active"
      add :permissions_snapshot, :map, default: %{}
      add :provisioned_at, :utc_datetime
      add :revoked_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:app_accounts, [:user_id, :application_id], unique: true)
  end

  def down do
    drop_if_exists index(:app_accounts, [:user_id, :application_id])

    drop table(:app_accounts)

    drop constraint(
           :application_admin_assignments,
           "application_admin_assignments_application_id_fkey"
         )

    drop constraint(:application_admin_assignments, "application_admin_assignments_user_id_fkey")

    drop_if_exists unique_index(:application_admin_assignments, [:application_id, :user_id],
                     name: "application_admin_assignments_unique_admin_assignment_index"
                   )

    drop table(:application_admin_assignments)

    drop constraint(:applications, "applications_organization_id_fkey")

    drop constraint(:applications, "applications_business_owner_id_fkey")

    drop constraint(:applications, "applications_approval_policy_id_fkey")

    alter table(:applications) do
      remove :updated_at
      remove :inserted_at
      remove :approval_policy_id
      remove :business_owner_id
      remove :integration_type
      remove :status
      remove :name
      remove :organization_id
    end

    drop constraint(:resources, "resources_application_id_fkey")

    drop constraint(:resources, "resources_parent_resource_id_fkey")

    alter table(:resources) do
      modify :parent_resource_id, :uuid
      modify :application_id, :uuid
    end

    drop table(:applications)

    drop constraint(:approval_policies, "approval_policies_organization_id_fkey")

    alter table(:approval_policies) do
      remove :updated_at
      remove :inserted_at
      remove :is_default
      remove :name
      remove :organization_id
    end

    drop constraint(:approval_steps, "approval_steps_approval_policy_id_fkey")

    alter table(:approval_steps) do
      modify :approval_policy_id, :uuid
    end

    drop table(:approval_policies)

    drop table(:approval_steps)

    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    alter table(:organizations) do
      remove :updated_at
      remove :inserted_at
      remove :slack_admin_channel_id
      remove :slack_hr_channel_id
      remove :slug
      remove :name
    end

    drop constraint(:users, "users_organization_id_fkey")

    drop constraint(:users, "users_manager_id_fkey")

    alter table(:users) do
      modify :manager_id, :uuid
      modify :organization_id, :uuid
    end

    drop table(:organizations)

    drop constraint(:permissions, "permissions_resource_id_fkey")

    drop table(:permissions)

    drop table(:resources)

    drop_if_exists unique_index(:users, [:organization_id, :email],
                     name: "users_unique_email_per_org_index"
                   )

    drop table(:users)
  end
end
