defmodule AccessGuardian.Repo.Migrations.CreateIntegrationSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:integration_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :platform, :text, null: false
      add :status, :text, null: false, default: "active"
      add :workspace_url, :text, null: false
      add :captured_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :application_id,
          references(:applications,
            column: :id,
            name: "integration_sessions_application_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:integration_sessions, "integration_sessions_application_id_fkey")

    drop table(:integration_sessions)
  end
end
