defmodule AccessGuardian.Repo.Migrations.AddAppConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:applications) do
      add :config, :map, default: %{}
    end
  end

  def down do
    alter table(:applications) do
      remove :config
    end
  end
end
