defmodule AccessGuardian.Repo.Migrations.CreateAccess do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:request_approvals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :access_request_id, :uuid, null: false
      add :approver_id, :uuid, null: false
      add :step_index, :bigint, null: false
      add :decision, :text, null: false
      add :override_by_id, :uuid
      add :decided_at, :utc_datetime, null: false
    end

    create table(:access_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:request_approvals) do
      modify :access_request_id,
             references(:access_requests,
               column: :id,
               name: "request_approvals_access_request_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :approver_id,
             references(:users,
               column: :id,
               name: "request_approvals_approver_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:access_requests) do
      add :organization_id, :uuid, null: false

      add :affected_user_id,
          references(:users,
            column: :id,
            name: "access_requests_affected_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :requested_by_id,
          references(:users,
            column: :id,
            name: "access_requests_requested_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :application_id,
          references(:applications,
            column: :id,
            name: "access_requests_application_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :status, :text, null: false, default: "pending_approval"
      add :request_reason, :text
      add :entitlements, :map, default: %{}
      add :current_step_index, :bigint, default: 0
      add :total_steps, :bigint, default: 0
      add :approved_at, :utc_datetime
      add :denied_at, :utc_datetime
      add :denied_by_id, :uuid
      add :deny_reason, :text
      add :granted_at, :utc_datetime
      add :rejected_at, :utc_datetime
      add :reject_reason, :text
      add :provisioner_type, :text
      add :adapter_type, :text
      add :external_account_id, :text
      add :pending_manual, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:access_requests, [:affected_user_id])

    create index(:access_requests, [:application_id])

    create index(:access_requests, [:organization_id, :status])
  end

  def down do
    drop constraint(:access_requests, "access_requests_affected_user_id_fkey")

    drop constraint(:access_requests, "access_requests_requested_by_id_fkey")

    drop constraint(:access_requests, "access_requests_application_id_fkey")

    drop_if_exists index(:access_requests, [:organization_id, :status])

    drop_if_exists index(:access_requests, [:application_id])

    drop_if_exists index(:access_requests, [:affected_user_id])

    alter table(:access_requests) do
      remove :updated_at
      remove :inserted_at
      remove :pending_manual
      remove :external_account_id
      remove :adapter_type
      remove :provisioner_type
      remove :reject_reason
      remove :rejected_at
      remove :granted_at
      remove :deny_reason
      remove :denied_by_id
      remove :denied_at
      remove :approved_at
      remove :total_steps
      remove :current_step_index
      remove :entitlements
      remove :request_reason
      remove :status
      remove :application_id
      remove :requested_by_id
      remove :affected_user_id
      remove :organization_id
    end

    drop constraint(:request_approvals, "request_approvals_access_request_id_fkey")

    drop constraint(:request_approvals, "request_approvals_approver_id_fkey")

    alter table(:request_approvals) do
      modify :approver_id, :uuid
      modify :access_request_id, :uuid
    end

    drop table(:access_requests)

    drop table(:request_approvals)
  end
end
