defmodule AccessGuardian.Repo.Migrations.AddLiveIntegration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:applications) do
      add :live_integration, :boolean, default: false
    end
  end

  def down do
    alter table(:applications) do
      remove :live_integration
    end
  end
end
